services:
  - type: web
    name: football-predictions-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  - type: cron
    name: daily-pick-automation
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python daily_pick.py
    schedule: "0 8 * * *"
    timezone: Europe/Madrid
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false 