name: Daily Pick Automation

on:
  schedule:
    # Run every day at 9 PM Spain time (8 PM UTC)
    - cron: '0 20 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-daily-pick:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Create daily pick
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        cd backend
        python3 daily_pick_automation.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add backend/data/processed/latest_data.json
        git commit -m "Auto-update daily pick $(date +%Y-%m-%d)" || exit 0
        git push 