name: Actualizar Transfermarkt DB

on:
  schedule:
    - cron: '0 4 * * *'  # Todos los días a las 4:00 UTC
  workflow_dispatch:

jobs:
  update-transfermarkt-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
      - name: Run Transfermarkt population script
        run: |
          python backend/populate_transfermarkt.py 