name: Actualizar estadísticas tipster Fut5Tips

on:
  schedule:
    - cron: '0 5 * * *' # Todos los días a las 5:00 UTC
  workflow_dispatch:

jobs:
  update-tipster-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Ejecutar scraper
        run: python backend/notbetting_scraper.py

      - name: Hacer commit y push si hay cambios
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add backend/data/tipster_stats.json
          git diff --cached --quiet || (git commit -m 'Actualización automática de estadísticas Fut5Tips' && git push) 