name: Actualizar datos integrados (cuotas, partidos, estadísticas)

on:
  schedule:
    - cron: '0 * * * *' # Cada hora
  workflow_dispatch:

jobs:
  update-integrated-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Ejecutar scripts de integración/scraping
        env:
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
          BETSAPI_KEY: ${{ secrets.BETSAPI_KEY }}
          SPORTMONKS_API_KEY: ${{ secrets.SPORTMONKS_API_KEY }}
        run: |
          python backend/odds_api_integration.py
          python backend/sportmonks_integration.py
          python backend/flashscore_scraper.py
          python backend/sofascore_scraper.py
          python backend/betexplorer_scraper.py

      - name: Hacer commit y push si hay cambios
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add backend/data/*.json
          git diff --cached --quiet || git commit -m "Actualización automática de datos integrados (cuotas, partidos, estadísticas)"
          git push 